//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.60818.0
// 
namespace SilverlightClassLibrary1.PvScoutService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAnwenderRequest", Namespace="http://schemas.datacontract.org/2004/07/pvscout.wcf.business.datacontracts.reques" +
        "ts")]
    public partial class GetAnwenderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anwender", Namespace="http://schemas.datacontract.org/2004/07/pvscout.wcf.business.datacontracts")]
    public partial class Anwender : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Bankverbindung1Field;
        
        private string Bankverbindung2Field;
        
        private string Bankverbindung3Field;
        
        private string Bankverbindung4Field;
        
        private string EmailField;
        
        private string FaxField;
        
        private string FirmaField;
        
        private string HRBField;
        
        private string InternetField;
        
        private string LandField;
        
        private string MobilField;
        
        private string NachNameField;
        
        private string OrtField;
        
        private string PLZField;
        
        private string PostfachField;
        
        private string StrasseField;
        
        private string TelefonField;
        
        private string UStIDField;
        
        private string VorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bankverbindung1 {
            get {
                return this.Bankverbindung1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Bankverbindung1Field, value) != true)) {
                    this.Bankverbindung1Field = value;
                    this.RaisePropertyChanged("Bankverbindung1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bankverbindung2 {
            get {
                return this.Bankverbindung2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Bankverbindung2Field, value) != true)) {
                    this.Bankverbindung2Field = value;
                    this.RaisePropertyChanged("Bankverbindung2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bankverbindung3 {
            get {
                return this.Bankverbindung3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Bankverbindung3Field, value) != true)) {
                    this.Bankverbindung3Field = value;
                    this.RaisePropertyChanged("Bankverbindung3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bankverbindung4 {
            get {
                return this.Bankverbindung4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Bankverbindung4Field, value) != true)) {
                    this.Bankverbindung4Field = value;
                    this.RaisePropertyChanged("Bankverbindung4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HRB {
            get {
                return this.HRBField;
            }
            set {
                if ((object.ReferenceEquals(this.HRBField, value) != true)) {
                    this.HRBField = value;
                    this.RaisePropertyChanged("HRB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Internet {
            get {
                return this.InternetField;
            }
            set {
                if ((object.ReferenceEquals(this.InternetField, value) != true)) {
                    this.InternetField = value;
                    this.RaisePropertyChanged("Internet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Land {
            get {
                return this.LandField;
            }
            set {
                if ((object.ReferenceEquals(this.LandField, value) != true)) {
                    this.LandField = value;
                    this.RaisePropertyChanged("Land");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobil {
            get {
                return this.MobilField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilField, value) != true)) {
                    this.MobilField = value;
                    this.RaisePropertyChanged("Mobil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NachName {
            get {
                return this.NachNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NachNameField, value) != true)) {
                    this.NachNameField = value;
                    this.RaisePropertyChanged("NachName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ort {
            get {
                return this.OrtField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtField, value) != true)) {
                    this.OrtField = value;
                    this.RaisePropertyChanged("Ort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLZ {
            get {
                return this.PLZField;
            }
            set {
                if ((object.ReferenceEquals(this.PLZField, value) != true)) {
                    this.PLZField = value;
                    this.RaisePropertyChanged("PLZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postfach {
            get {
                return this.PostfachField;
            }
            set {
                if ((object.ReferenceEquals(this.PostfachField, value) != true)) {
                    this.PostfachField = value;
                    this.RaisePropertyChanged("Postfach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Strasse {
            get {
                return this.StrasseField;
            }
            set {
                if ((object.ReferenceEquals(this.StrasseField, value) != true)) {
                    this.StrasseField = value;
                    this.RaisePropertyChanged("Strasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UStID {
            get {
                return this.UStIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UStIDField, value) != true)) {
                    this.UStIDField = value;
                    this.RaisePropertyChanged("UStID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VorName {
            get {
                return this.VorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VorNameField, value) != true)) {
                    this.VorNameField = value;
                    this.RaisePropertyChanged("VorName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PvScoutService.IPvscoutService")]
    public interface IPvscoutService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPvscoutService/Ping", ReplyAction="http://tempuri.org/IPvscoutService/PingResponse")]
        System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState);
        
        string EndPing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPvscoutService/GetAnwender", ReplyAction="http://tempuri.org/IPvscoutService/GetAnwenderResponse")]
        System.IAsyncResult BeginGetAnwender(SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightClassLibrary1.PvScoutService.Anwender EndGetAnwender(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPvscoutServiceChannel : SilverlightClassLibrary1.PvScoutService.IPvscoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAnwenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAnwenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightClassLibrary1.PvScoutService.Anwender Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightClassLibrary1.PvScoutService.Anwender)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PvscoutServiceClient : System.ServiceModel.ClientBase<SilverlightClassLibrary1.PvScoutService.IPvscoutService>, SilverlightClassLibrary1.PvScoutService.IPvscoutService {
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAnwenderDelegate;
        
        private EndOperationDelegate onEndGetAnwenderDelegate;
        
        private System.Threading.SendOrPostCallback onGetAnwenderCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PvscoutServiceClient() {
        }
        
        public PvscoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PvscoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvscoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvscoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PingCompletedEventArgs> PingCompleted;
        
        public event System.EventHandler<GetAnwenderCompletedEventArgs> GetAnwenderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightClassLibrary1.PvScoutService.IPvscoutService.BeginPing(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SilverlightClassLibrary1.PvScoutService.IPvscoutService.EndPing(System.IAsyncResult result) {
            return base.Channel.EndPing(result);
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightClassLibrary1.PvScoutService.IPvscoutService)(this)).BeginPing(callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            string retVal = ((SilverlightClassLibrary1.PvScoutService.IPvscoutService)(this)).EndPing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new PingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        public void PingAsync(object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, null, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightClassLibrary1.PvScoutService.IPvscoutService.BeginGetAnwender(SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAnwender(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightClassLibrary1.PvScoutService.Anwender SilverlightClassLibrary1.PvScoutService.IPvscoutService.EndGetAnwender(System.IAsyncResult result) {
            return base.Channel.EndGetAnwender(result);
        }
        
        private System.IAsyncResult OnBeginGetAnwender(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request = ((SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest)(inValues[0]));
            return ((SilverlightClassLibrary1.PvScoutService.IPvscoutService)(this)).BeginGetAnwender(request, callback, asyncState);
        }
        
        private object[] OnEndGetAnwender(System.IAsyncResult result) {
            SilverlightClassLibrary1.PvScoutService.Anwender retVal = ((SilverlightClassLibrary1.PvScoutService.IPvscoutService)(this)).EndGetAnwender(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAnwenderCompleted(object state) {
            if ((this.GetAnwenderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAnwenderCompleted(this, new GetAnwenderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAnwenderAsync(SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request) {
            this.GetAnwenderAsync(request, null);
        }
        
        public void GetAnwenderAsync(SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request, object userState) {
            if ((this.onBeginGetAnwenderDelegate == null)) {
                this.onBeginGetAnwenderDelegate = new BeginOperationDelegate(this.OnBeginGetAnwender);
            }
            if ((this.onEndGetAnwenderDelegate == null)) {
                this.onEndGetAnwenderDelegate = new EndOperationDelegate(this.OnEndGetAnwender);
            }
            if ((this.onGetAnwenderCompletedDelegate == null)) {
                this.onGetAnwenderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAnwenderCompleted);
            }
            base.InvokeAsync(this.onBeginGetAnwenderDelegate, new object[] {
                        request}, this.onEndGetAnwenderDelegate, this.onGetAnwenderCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightClassLibrary1.PvScoutService.IPvscoutService CreateChannel() {
            return new PvscoutServiceClientChannel(this);
        }
        
        private class PvscoutServiceClientChannel : ChannelBase<SilverlightClassLibrary1.PvScoutService.IPvscoutService>, SilverlightClassLibrary1.PvScoutService.IPvscoutService {
            
            public PvscoutServiceClientChannel(System.ServiceModel.ClientBase<SilverlightClassLibrary1.PvScoutService.IPvscoutService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Ping", _args, callback, asyncState);
                return _result;
            }
            
            public string EndPing(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Ping", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAnwender(SilverlightClassLibrary1.PvScoutService.GetAnwenderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAnwender", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightClassLibrary1.PvScoutService.Anwender EndGetAnwender(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightClassLibrary1.PvScoutService.Anwender _result = ((SilverlightClassLibrary1.PvScoutService.Anwender)(base.EndInvoke("GetAnwender", _args, result)));
                return _result;
            }
        }
    }
}
