//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace PvScoutWeb.PvScoutService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PvModuleActual", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    public partial class PvModuleActual : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double HeightField;
        
        private int IdField;
        
        private double LeftField;
        
        private double TopField;
        
        private double WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PvModule", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    public partial class PvModule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PvScoutWeb.PvScoutService.PvModuleActual ObjPvModuleActualField;
        
        private PvScoutWeb.PvScoutService.PvModuleVirtual ObjPvModuleVirtualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PvScoutWeb.PvScoutService.PvModuleActual ObjPvModuleActual {
            get {
                return this.ObjPvModuleActualField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjPvModuleActualField, value) != true)) {
                    this.ObjPvModuleActualField = value;
                    this.RaisePropertyChanged("ObjPvModuleActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PvScoutWeb.PvScoutService.PvModuleVirtual ObjPvModuleVirtual {
            get {
                return this.ObjPvModuleVirtualField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjPvModuleVirtualField, value) != true)) {
                    this.ObjPvModuleVirtualField = value;
                    this.RaisePropertyChanged("ObjPvModuleVirtual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PvModuleVirtual", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    public partial class PvModuleVirtual : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double HeightField;
        
        private int IdField;
        
        private double LeftField;
        
        private double TopField;
        
        private double WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PvScoutService.IPvScoutService")]
    public interface IPvScoutService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPvScoutService/GetPvModulePosition", ReplyAction="http://tempuri.org/IPvScoutService/GetPvModulePositionResponse")]
        System.IAsyncResult BeginGetPvModulePosition(PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual, System.AsyncCallback callback, object asyncState);
        
        PvScoutWeb.PvScoutService.PvModule EndGetPvModulePosition(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPvScoutService/Hello", ReplyAction="http://tempuri.org/IPvScoutService/HelloResponse")]
        System.IAsyncResult BeginHello(System.AsyncCallback callback, object asyncState);
        
        string EndHello(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPvScoutServiceChannel : PvScoutWeb.PvScoutService.IPvScoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPvModulePositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPvModulePositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PvScoutWeb.PvScoutService.PvModule Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PvScoutWeb.PvScoutService.PvModule)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PvScoutServiceClient : System.ServiceModel.ClientBase<PvScoutWeb.PvScoutService.IPvScoutService>, PvScoutWeb.PvScoutService.IPvScoutService {
        
        private BeginOperationDelegate onBeginGetPvModulePositionDelegate;
        
        private EndOperationDelegate onEndGetPvModulePositionDelegate;
        
        private System.Threading.SendOrPostCallback onGetPvModulePositionCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloDelegate;
        
        private EndOperationDelegate onEndHelloDelegate;
        
        private System.Threading.SendOrPostCallback onHelloCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PvScoutServiceClient() {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvScoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPvModulePositionCompletedEventArgs> GetPvModulePositionCompleted;
        
        public event System.EventHandler<HelloCompletedEventArgs> HelloCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PvScoutWeb.PvScoutService.IPvScoutService.BeginGetPvModulePosition(PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPvModulePosition(objPvModuleActual, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PvScoutWeb.PvScoutService.PvModule PvScoutWeb.PvScoutService.IPvScoutService.EndGetPvModulePosition(System.IAsyncResult result) {
            return base.Channel.EndGetPvModulePosition(result);
        }
        
        private System.IAsyncResult OnBeginGetPvModulePosition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual = ((PvScoutWeb.PvScoutService.PvModuleActual)(inValues[0]));
            return ((PvScoutWeb.PvScoutService.IPvScoutService)(this)).BeginGetPvModulePosition(objPvModuleActual, callback, asyncState);
        }
        
        private object[] OnEndGetPvModulePosition(System.IAsyncResult result) {
            PvScoutWeb.PvScoutService.PvModule retVal = ((PvScoutWeb.PvScoutService.IPvScoutService)(this)).EndGetPvModulePosition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPvModulePositionCompleted(object state) {
            if ((this.GetPvModulePositionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPvModulePositionCompleted(this, new GetPvModulePositionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPvModulePositionAsync(PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual) {
            this.GetPvModulePositionAsync(objPvModuleActual, null);
        }
        
        public void GetPvModulePositionAsync(PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual, object userState) {
            if ((this.onBeginGetPvModulePositionDelegate == null)) {
                this.onBeginGetPvModulePositionDelegate = new BeginOperationDelegate(this.OnBeginGetPvModulePosition);
            }
            if ((this.onEndGetPvModulePositionDelegate == null)) {
                this.onEndGetPvModulePositionDelegate = new EndOperationDelegate(this.OnEndGetPvModulePosition);
            }
            if ((this.onGetPvModulePositionCompletedDelegate == null)) {
                this.onGetPvModulePositionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPvModulePositionCompleted);
            }
            base.InvokeAsync(this.onBeginGetPvModulePositionDelegate, new object[] {
                        objPvModuleActual}, this.onEndGetPvModulePositionDelegate, this.onGetPvModulePositionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PvScoutWeb.PvScoutService.IPvScoutService.BeginHello(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHello(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PvScoutWeb.PvScoutService.IPvScoutService.EndHello(System.IAsyncResult result) {
            return base.Channel.EndHello(result);
        }
        
        private System.IAsyncResult OnBeginHello(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PvScoutWeb.PvScoutService.IPvScoutService)(this)).BeginHello(callback, asyncState);
        }
        
        private object[] OnEndHello(System.IAsyncResult result) {
            string retVal = ((PvScoutWeb.PvScoutService.IPvScoutService)(this)).EndHello(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloCompleted(object state) {
            if ((this.HelloCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloCompleted(this, new HelloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloAsync() {
            this.HelloAsync(null);
        }
        
        public void HelloAsync(object userState) {
            if ((this.onBeginHelloDelegate == null)) {
                this.onBeginHelloDelegate = new BeginOperationDelegate(this.OnBeginHello);
            }
            if ((this.onEndHelloDelegate == null)) {
                this.onEndHelloDelegate = new EndOperationDelegate(this.OnEndHello);
            }
            if ((this.onHelloCompletedDelegate == null)) {
                this.onHelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloCompleted);
            }
            base.InvokeAsync(this.onBeginHelloDelegate, null, this.onEndHelloDelegate, this.onHelloCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PvScoutWeb.PvScoutService.IPvScoutService CreateChannel() {
            return new PvScoutServiceClientChannel(this);
        }
        
        private class PvScoutServiceClientChannel : ChannelBase<PvScoutWeb.PvScoutService.IPvScoutService>, PvScoutWeb.PvScoutService.IPvScoutService {
            
            public PvScoutServiceClientChannel(System.ServiceModel.ClientBase<PvScoutWeb.PvScoutService.IPvScoutService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPvModulePosition(PvScoutWeb.PvScoutService.PvModuleActual objPvModuleActual, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = objPvModuleActual;
                System.IAsyncResult _result = base.BeginInvoke("GetPvModulePosition", _args, callback, asyncState);
                return _result;
            }
            
            public PvScoutWeb.PvScoutService.PvModule EndGetPvModulePosition(System.IAsyncResult result) {
                object[] _args = new object[0];
                PvScoutWeb.PvScoutService.PvModule _result = ((PvScoutWeb.PvScoutService.PvModule)(base.EndInvoke("GetPvModulePosition", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHello(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Hello", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHello(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Hello", _args, result)));
                return _result;
            }
        }
    }
}
