//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace SilverLightClient.ProductServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    public partial class Manufacturer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AddressField;
        
        private string DescriptionField;
        
        private int ManufIdField;
        
        private string ManufNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufId {
            get {
                return this.ManufIdField;
            }
            set {
                if ((this.ManufIdField.Equals(value) != true)) {
                    this.ManufIdField = value;
                    this.RaisePropertyChanged("ManufId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufName {
            get {
                return this.ManufNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufNameField, value) != true)) {
                    this.ManufNameField = value;
                    this.RaisePropertyChanged("ManufName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceRef.IManufacturerService")]
    public interface IManufacturerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IManufacturerService/GetAllManufacturers", ReplyAction="http://tempuri.org/IManufacturerService/GetAllManufacturersResponse")]
        System.IAsyncResult BeginGetAllManufacturers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> EndGetAllManufacturers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManufacturerServiceChannel : SilverLightClient.ProductServiceRef.IManufacturerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllManufacturersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllManufacturersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturerServiceClient : System.ServiceModel.ClientBase<SilverLightClient.ProductServiceRef.IManufacturerService>, SilverLightClient.ProductServiceRef.IManufacturerService {
        
        private BeginOperationDelegate onBeginGetAllManufacturersDelegate;
        
        private EndOperationDelegate onEndGetAllManufacturersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllManufacturersCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ManufacturerServiceClient() {
        }
        
        public ManufacturerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllManufacturersCompletedEventArgs> GetAllManufacturersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLightClient.ProductServiceRef.IManufacturerService.BeginGetAllManufacturers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllManufacturers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> SilverLightClient.ProductServiceRef.IManufacturerService.EndGetAllManufacturers(System.IAsyncResult result) {
            return base.Channel.EndGetAllManufacturers(result);
        }
        
        private System.IAsyncResult OnBeginGetAllManufacturers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverLightClient.ProductServiceRef.IManufacturerService)(this)).BeginGetAllManufacturers(callback, asyncState);
        }
        
        private object[] OnEndGetAllManufacturers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> retVal = ((SilverLightClient.ProductServiceRef.IManufacturerService)(this)).EndGetAllManufacturers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllManufacturersCompleted(object state) {
            if ((this.GetAllManufacturersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllManufacturersCompleted(this, new GetAllManufacturersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllManufacturersAsync() {
            this.GetAllManufacturersAsync(null);
        }
        
        public void GetAllManufacturersAsync(object userState) {
            if ((this.onBeginGetAllManufacturersDelegate == null)) {
                this.onBeginGetAllManufacturersDelegate = new BeginOperationDelegate(this.OnBeginGetAllManufacturers);
            }
            if ((this.onEndGetAllManufacturersDelegate == null)) {
                this.onEndGetAllManufacturersDelegate = new EndOperationDelegate(this.OnEndGetAllManufacturers);
            }
            if ((this.onGetAllManufacturersCompletedDelegate == null)) {
                this.onGetAllManufacturersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllManufacturersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllManufacturersDelegate, null, this.onEndGetAllManufacturersDelegate, this.onGetAllManufacturersCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverLightClient.ProductServiceRef.IManufacturerService CreateChannel() {
            return new ManufacturerServiceClientChannel(this);
        }
        
        private class ManufacturerServiceClientChannel : ChannelBase<SilverLightClient.ProductServiceRef.IManufacturerService>, SilverLightClient.ProductServiceRef.IManufacturerService {
            
            public ManufacturerServiceClientChannel(System.ServiceModel.ClientBase<SilverLightClient.ProductServiceRef.IManufacturerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllManufacturers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllManufacturers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> EndGetAllManufacturers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverLightClient.ProductServiceRef.Manufacturer>)(base.EndInvoke("GetAllManufacturers", _args, result)));
                return _result;
            }
        }
    }
}
