//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightWcfTest.Web.PvScoutService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoofType", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    [System.SerializableAttribute()]
    public partial class RoofType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoofTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoofTypeId {
            get {
                return this.RoofTypeIdField;
            }
            set {
                if ((this.RoofTypeIdField.Equals(value) != true)) {
                    this.RoofTypeIdField = value;
                    this.RaisePropertyChanged("RoofTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PvModule", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    [System.SerializableAttribute()]
    public partial class PvModule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellTechnologyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PvScoutArticleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThicknessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleNumber {
            get {
                return this.ArticleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleNumberField, value) != true)) {
                    this.ArticleNumberField = value;
                    this.RaisePropertyChanged("ArticleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellMaterial {
            get {
                return this.CellMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.CellMaterialField, value) != true)) {
                    this.CellMaterialField = value;
                    this.RaisePropertyChanged("CellMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellTechnology {
            get {
                return this.CellTechnologyField;
            }
            set {
                if ((object.ReferenceEquals(this.CellTechnologyField, value) != true)) {
                    this.CellTechnologyField = value;
                    this.RaisePropertyChanged("CellTechnology");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerIdField, value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PvScoutArticleNumber {
            get {
                return this.PvScoutArticleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PvScoutArticleNumberField, value) != true)) {
                    this.PvScoutArticleNumberField = value;
                    this.RaisePropertyChanged("PvScoutArticleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Thickness {
            get {
                return this.ThicknessField;
            }
            set {
                if ((this.ThicknessField.Equals(value) != true)) {
                    this.ThicknessField = value;
                    this.RaisePropertyChanged("Thickness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    [System.SerializableAttribute()]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufId {
            get {
                return this.ManufIdField;
            }
            set {
                if ((this.ManufIdField.Equals(value) != true)) {
                    this.ManufIdField = value;
                    this.RaisePropertyChanged("ManufId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufName {
            get {
                return this.ManufNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufNameField, value) != true)) {
                    this.ManufNameField = value;
                    this.RaisePropertyChanged("ManufName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRoof", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    [System.SerializableAttribute()]
    public partial class BaseRoof : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SilverlightWcfTest.Web.PvScoutService.ConstructionOrientationEnum ConstructionOrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DrawableLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DrawableWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FirstSparrenDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InterSparrenDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ModuleDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModulesPerColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModulesPerRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SilverlightWcfTest.Web.PvScoutService.PvModule[] PvModulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RoofHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RoofLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RoofOrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RoofPitchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RoofWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SilverlightWcfTest.Web.PvScoutService.PvModule SelectedPvModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SilverlightWcfTest.Web.PvScoutService.RoofType SelectedRoofTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SparrenWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SilverlightWcfTest.Web.PvScoutService.Sparren[] SparrensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZoomLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightWcfTest.Web.PvScoutService.ConstructionOrientationEnum ConstructionOrientation {
            get {
                return this.ConstructionOrientationField;
            }
            set {
                if ((this.ConstructionOrientationField.Equals(value) != true)) {
                    this.ConstructionOrientationField = value;
                    this.RaisePropertyChanged("ConstructionOrientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DrawableLength {
            get {
                return this.DrawableLengthField;
            }
            set {
                if ((this.DrawableLengthField.Equals(value) != true)) {
                    this.DrawableLengthField = value;
                    this.RaisePropertyChanged("DrawableLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DrawableWidth {
            get {
                return this.DrawableWidthField;
            }
            set {
                if ((this.DrawableWidthField.Equals(value) != true)) {
                    this.DrawableWidthField = value;
                    this.RaisePropertyChanged("DrawableWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FirstSparrenDistance {
            get {
                return this.FirstSparrenDistanceField;
            }
            set {
                if ((this.FirstSparrenDistanceField.Equals(value) != true)) {
                    this.FirstSparrenDistanceField = value;
                    this.RaisePropertyChanged("FirstSparrenDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InterSparrenDistance {
            get {
                return this.InterSparrenDistanceField;
            }
            set {
                if ((this.InterSparrenDistanceField.Equals(value) != true)) {
                    this.InterSparrenDistanceField = value;
                    this.RaisePropertyChanged("InterSparrenDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ModuleDistance {
            get {
                return this.ModuleDistanceField;
            }
            set {
                if ((this.ModuleDistanceField.Equals(value) != true)) {
                    this.ModuleDistanceField = value;
                    this.RaisePropertyChanged("ModuleDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModulesPerColumn {
            get {
                return this.ModulesPerColumnField;
            }
            set {
                if ((this.ModulesPerColumnField.Equals(value) != true)) {
                    this.ModulesPerColumnField = value;
                    this.RaisePropertyChanged("ModulesPerColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModulesPerRow {
            get {
                return this.ModulesPerRowField;
            }
            set {
                if ((this.ModulesPerRowField.Equals(value) != true)) {
                    this.ModulesPerRowField = value;
                    this.RaisePropertyChanged("ModulesPerRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightWcfTest.Web.PvScoutService.PvModule[] PvModules {
            get {
                return this.PvModulesField;
            }
            set {
                if ((object.ReferenceEquals(this.PvModulesField, value) != true)) {
                    this.PvModulesField = value;
                    this.RaisePropertyChanged("PvModules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RoofHeight {
            get {
                return this.RoofHeightField;
            }
            set {
                if ((this.RoofHeightField.Equals(value) != true)) {
                    this.RoofHeightField = value;
                    this.RaisePropertyChanged("RoofHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RoofLength {
            get {
                return this.RoofLengthField;
            }
            set {
                if ((this.RoofLengthField.Equals(value) != true)) {
                    this.RoofLengthField = value;
                    this.RaisePropertyChanged("RoofLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RoofOrientation {
            get {
                return this.RoofOrientationField;
            }
            set {
                if ((this.RoofOrientationField.Equals(value) != true)) {
                    this.RoofOrientationField = value;
                    this.RaisePropertyChanged("RoofOrientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RoofPitch {
            get {
                return this.RoofPitchField;
            }
            set {
                if ((this.RoofPitchField.Equals(value) != true)) {
                    this.RoofPitchField = value;
                    this.RaisePropertyChanged("RoofPitch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RoofWidth {
            get {
                return this.RoofWidthField;
            }
            set {
                if ((this.RoofWidthField.Equals(value) != true)) {
                    this.RoofWidthField = value;
                    this.RaisePropertyChanged("RoofWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightWcfTest.Web.PvScoutService.PvModule SelectedPvModule {
            get {
                return this.SelectedPvModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedPvModuleField, value) != true)) {
                    this.SelectedPvModuleField = value;
                    this.RaisePropertyChanged("SelectedPvModule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightWcfTest.Web.PvScoutService.RoofType SelectedRoofType {
            get {
                return this.SelectedRoofTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedRoofTypeField, value) != true)) {
                    this.SelectedRoofTypeField = value;
                    this.RaisePropertyChanged("SelectedRoofType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SparrenWidth {
            get {
                return this.SparrenWidthField;
            }
            set {
                if ((this.SparrenWidthField.Equals(value) != true)) {
                    this.SparrenWidthField = value;
                    this.RaisePropertyChanged("SparrenWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightWcfTest.Web.PvScoutService.Sparren[] Sparrens {
            get {
                return this.SparrensField;
            }
            set {
                if ((object.ReferenceEquals(this.SparrensField, value) != true)) {
                    this.SparrensField = value;
                    this.RaisePropertyChanged("Sparrens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ZoomLevel {
            get {
                return this.ZoomLevelField;
            }
            set {
                if ((this.ZoomLevelField.Equals(value) != true)) {
                    this.ZoomLevelField = value;
                    this.RaisePropertyChanged("ZoomLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstructionOrientationEnum", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    public enum ConstructionOrientationEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sparrendach = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pfettendach = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sparren", Namespace="http://schemas.datacontract.org/2004/07/Solar.Pvscout.Business.Entity")]
    [System.SerializableAttribute()]
    public partial class Sparren : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LeftVirtualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopVirtualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LeftVirtual {
            get {
                return this.LeftVirtualField;
            }
            set {
                if ((this.LeftVirtualField.Equals(value) != true)) {
                    this.LeftVirtualField = value;
                    this.RaisePropertyChanged("LeftVirtual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TopVirtual {
            get {
                return this.TopVirtualField;
            }
            set {
                if ((this.TopVirtualField.Equals(value) != true)) {
                    this.TopVirtualField = value;
                    this.RaisePropertyChanged("TopVirtual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PvScoutService.IPvScoutService")]
    public interface IPvScoutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/Ping", ReplyAction="http://tempuri.org/IPvScoutService/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetAllRoofTypes", ReplyAction="http://tempuri.org/IPvScoutService/GetAllRoofTypesResponse")]
        SilverlightWcfTest.Web.PvScoutService.RoofType[] GetAllRoofTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetRoofType", ReplyAction="http://tempuri.org/IPvScoutService/GetRoofTypeResponse")]
        SilverlightWcfTest.Web.PvScoutService.RoofType GetRoofType(string roofId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetAllPvModules", ReplyAction="http://tempuri.org/IPvScoutService/GetAllPvModulesResponse")]
        SilverlightWcfTest.Web.PvScoutService.PvModule[] GetAllPvModules(string manufacturerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetManufacturer", ReplyAction="http://tempuri.org/IPvScoutService/GetManufacturerResponse")]
        SilverlightWcfTest.Web.PvScoutService.Manufacturer GetManufacturer(string manufacturerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetAllManufacturers", ReplyAction="http://tempuri.org/IPvScoutService/GetAllManufacturersResponse")]
        SilverlightWcfTest.Web.PvScoutService.Manufacturer[] GetAllManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/GetPvModule", ReplyAction="http://tempuri.org/IPvScoutService/GetPvModuleResponse")]
        SilverlightWcfTest.Web.PvScoutService.PvModule GetPvModule(string pvscoutArticleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/FillRoof", ReplyAction="http://tempuri.org/IPvScoutService/FillRoofResponse")]
        SilverlightWcfTest.Web.PvScoutService.BaseRoof FillRoof(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/DrawRoof", ReplyAction="http://tempuri.org/IPvScoutService/DrawRoofResponse")]
        SilverlightWcfTest.Web.PvScoutService.BaseRoof DrawRoof(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPvScoutService/VerifyModuleDropPosition", ReplyAction="http://tempuri.org/IPvScoutService/VerifyModuleDropPositionResponse")]
        bool VerifyModuleDropPosition(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof, SilverlightWcfTest.Web.PvScoutService.PvModule movedModule, int newLeft, int newTop);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPvScoutServiceChannel : SilverlightWcfTest.Web.PvScoutService.IPvScoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PvScoutServiceClient : System.ServiceModel.ClientBase<SilverlightWcfTest.Web.PvScoutService.IPvScoutService>, SilverlightWcfTest.Web.PvScoutService.IPvScoutService {
        
        public PvScoutServiceClient() {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvScoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PvScoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public SilverlightWcfTest.Web.PvScoutService.RoofType[] GetAllRoofTypes() {
            return base.Channel.GetAllRoofTypes();
        }
        
        public SilverlightWcfTest.Web.PvScoutService.RoofType GetRoofType(string roofId) {
            return base.Channel.GetRoofType(roofId);
        }
        
        public SilverlightWcfTest.Web.PvScoutService.PvModule[] GetAllPvModules(string manufacturerId) {
            return base.Channel.GetAllPvModules(manufacturerId);
        }
        
        public SilverlightWcfTest.Web.PvScoutService.Manufacturer GetManufacturer(string manufacturerId) {
            return base.Channel.GetManufacturer(manufacturerId);
        }
        
        public SilverlightWcfTest.Web.PvScoutService.Manufacturer[] GetAllManufacturers() {
            return base.Channel.GetAllManufacturers();
        }
        
        public SilverlightWcfTest.Web.PvScoutService.PvModule GetPvModule(string pvscoutArticleNumber) {
            return base.Channel.GetPvModule(pvscoutArticleNumber);
        }
        
        public SilverlightWcfTest.Web.PvScoutService.BaseRoof FillRoof(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof) {
            return base.Channel.FillRoof(objRoof);
        }
        
        public SilverlightWcfTest.Web.PvScoutService.BaseRoof DrawRoof(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof) {
            return base.Channel.DrawRoof(objRoof);
        }
        
        public bool VerifyModuleDropPosition(SilverlightWcfTest.Web.PvScoutService.BaseRoof objRoof, SilverlightWcfTest.Web.PvScoutService.PvModule movedModule, int newLeft, int newTop) {
            return base.Channel.VerifyModuleDropPosition(objRoof, movedModule, newLeft, newTop);
        }
    }
}
